baseURL = 'http://example.org/' 
copyright = "{year}" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
defaultContentLanguage = 'en' 
enableRobotsTXT = true 
languageCode = 'en-US' 
paginate = 5 
summaryLength = 15 
theme = 'enchanted-lowkey' 
title = 'Just another blog' 

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = true
noHl = false
style = 'dracula'
tabWidth = 4
