[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 2

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 3

# Social Media Configuration

[[social]]
    identifier = "shopify"
    name = "Shopify"
    url = "https://jetjone.myshopify.com/"
    weight = 1

[[social]]
    identifier = "ebay"
    name = "eBay"
    url = "https://www.ebay.com/str/jetjone"
    weight = 2

[[social]]
    identifier = "wed2c"
    name = "Wed2c"
    url = "https://jetjone2.wed2c.com/"
    weight = 3